version: 2

jobs:
  build:
    docker:
      - image: circleci/python 
    steps:
      - checkout
      - run: 
          command: |
            pip install selenium
            pp install chromedriver-binary 
      - run: 
          command: python execute.py IPV4 LOGIN_PASSWD SSH_PASSWD
