version: 2

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run: 
          command: |
            sudo apt -y update
            sudo apt -y install python-pip
            sudo pip install selenium
      - run: 
          command: python execute.py IPV4 LOGIN_PASSWD SSH_PASSWD
