version: 2

jobs:
  build:
    docker:
      - image: circleci/python 
    steps:
      - checkout
      - run: 
          command: |
            sudo apt install -y chromium-browser
            sudo pip install selenium
            sudo pip install chromedriver-binary 
      - run: 
          command: python execute.py IPV4 LOGIN_PASSWD SSH_PASSWD
